#!/bin/sh

export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
export GOPATH=$HOME/.local/share/go

export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home

export MANPAGER='lvim +Man!'
