#!/bin/sh

fish_add_path -m ~/.local/bin
fish_add_path $HOME/.cargo/bin

fish_add_path $ANDROID_SDK_ROOT/emulator
fish_add_path $ANDROID_SDK_ROOT/tools
fish_add_path $ANDROID_SDK_ROOT/tools/bin
fish_add_path $ANDROID_SDK_ROOT/platform-tools

fish_add_path /.cargo/bin:$PATH
fish_add_path /.local/share/go/bin:$PATH
fish_add_path /.local/share/go
